AWSTemplateFormatVersion: 2010-09-09
Description: --- Setup foundation required for CloudFormation Cross Account access on the Primary account

Parameters:
  LFDatabaseName:
    Type: String
    Default: lf-ml
  ProducerStewardUserPassword:
    Type: String
    NoEcho: 'true'
    AllowedPattern: >-
      ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+-\[\]\{\}|???])[A-Za-z\d!@#$%^&*()_+-\[\]\{\}|???]{8,}$
    ConstraintDescription: >-
      Password should be a min. of 8 characters, include a min. of three of the
      following mix of character types: uppercase, lowercase, numbers,
      non-alphanumeric symbols
    Description: >-
      Password for Data Steward user. Should be a min. of 8 characters, include
      a min. of three of the following mix of character types: uppercase,
      lowercase, numbers, non-alphanumeric symbols, for example
      !@#$%^&*()_+-[]{}|??? and not be identical to your AWS account name or
      email address
  CentralAccountID:
    Type: String
  CentralAccountLFServiceRole:
    Type: String

Resources: 
  # custom resource to load data into the s3 bucket when this stack is first deployed
  # we use an inlined lambda functions to keep things simple!
  LoadDataBucketRole:
    Type: "AWS::IAM::Role"
    Properties:     
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Principal: 
                Service: 
                  - "lambda.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - !Ref LoadDataS3Policy

  LoadDataS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: S3 and KMS Key Access for the Load Data Lambda
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !GetAtt creditBucket.Arn
              - !Join [ '', [!GetAtt creditBucket.Arn, '/*']]
              - "arn:aws:s3:::aws-blogs-artifacts-public/artifacts/ML-8551/*"
          - Effect: "Allow"
            Action:
              - lakeformation:GrantPermissions
            Resource: '*'

  LFDataLakeSettingsLambda:
    Type: AWS::LakeFormation::DataLakeSettings
    DependsOn: 
      - LoadDataBucketRole
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: !GetAtt 'LoadDataBucketRole.Arn'
     
  LoadDataBucketLambda:
    Type: AWS::Lambda::Function
    DependsOn: 
      - LoadDataS3Policy
      - AWSGlueServiceRole
    Properties:
      Description: Custom Resource Lambda that loads the data bucket
      Handler: index.handler
      Runtime: python3.7
      Timeout: 300
      Role: !GetAtt LoadDataBucketRole.Arn
      Code:
        ZipFile: |
          import os
          import boto3
          import cfnresponse
          import urllib.request
          import time
          def handler(event, context):
            try:
              credit_card_bucket_name = os.environ.get("CREDIT_CARD_DATA_BUCKET")
              central_account_id = os.environ.get("CENTRAL_ACCOUNT_ID")
              lf_principal = os.environ.get("GLUE_SERVICE_ROLE")
              producer_account_id = boto3.client('sts').get_caller_identity().get('Account')
              source_bucket = 'aws-blogs-artifacts-public'
              # copy data to customer s3 bucket
              s3 = boto3.resource('s3')
              # copy data to credit card s3 bucket
              data_copy_source = {
                  'Bucket': source_bucket,
                  'Key': 'artifacts/ML-8551/dataset/credit_card.csv'
              }
              bucket = s3.Bucket(credit_card_bucket_name)
              bucket.copy(data_copy_source, 'credit_card/credit_card.csv')
              #Grant permissions on the S3 bucket locations corresponding to cards and retail producers to the AWS Glue crawler role.
              lf_client = boto3.client('lakeformation')
              credit_card_bucket_arn = 'arn:aws:s3:::' + credit_card_bucket_name
              lf_client.grant_permissions(
                Principal={
                    'DataLakePrincipalIdentifier': lf_principal
                },
                Resource={
                  'DataLocation' : {
                    'CatalogId': central_account_id,
                    'ResourceArn': credit_card_bucket_arn
                  }
                },
                Permissions=['CREATE_TABLE_READ_WRITE']
              )
              # signal
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, context.log_stream_name)
            except Exception as err:
              print("Error in Custom Resource", err)
              # signal
              cfnresponse.send(event, context, cfnresponse.FAILED, {}, context.log_stream_name)
      Environment:
        Variables:
          CREDIT_CARD_DATA_BUCKET: !Ref creditBucket
          CENTRAL_ACCOUNT_ID: !Ref CentralAccountID
          GLUE_SERVICE_ROLE: !GetAtt AWSGlueServiceRole.Arn
            
  LoadDataBucket: 
      Type: Custom::LoadDataBucket
      Properties:
        ServiceToken: !GetAtt LoadDataBucketLambda.Arn

  glueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Glue Database for Lake Formation Cross Account
        Name: !Ref LFDatabaseName
        Parameters: { "CreateTableDefaultPermissions": "" }

  creditBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub "credit-card-lf-${AWS::AccountId}-${AWS::Region}"                
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  creditBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref creditBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Join [ '', ['arn:aws:iam::', !Ref CentralAccountID, ':role/', !Ref CentralAccountLFServiceRole]]
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub ${creditBucket.Arn}/*
              - !Sub ${creditBucket.Arn}


  AWSGlueServiceRole:
    Type: AWS::IAM::Role
    Properties :
      Description: IAM Role to crawl the files in the Amazon S3 data lake
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement :
          -
            Effect : Allow
            Principal :
              Service :
                - glue.amazonaws.com
                - lakeformation.amazonaws.com
            Action :
              - sts:AssumeRole
      Path: /    
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - !Ref CrawlerS3Policy

  CrawlerS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Crawler policy to access the source s3 bucket
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - !GetAtt creditBucket.Arn
              - !Join [ '', [!GetAtt creditBucket.Arn, '/*']]


  GlueCrawlerCards:
    DependsOn:
      - creditBucket
      - LoadDataBucket
    Type: AWS::Glue::Crawler
    Properties:
        Role: !GetAtt AWSGlueServiceRole.Arn
        Name: !Sub "creditCrawler-${AWS::AccountId}"
        DatabaseName: !Ref LFDatabaseName
        Targets:
          S3Targets:
            - Path: !Join [ '', [!Ref creditBucket, '/creditcards/']]
  ProducerStewardUser:
    Type: 'AWS::IAM::User'
    Properties:
      Path: /
      LoginProfile:
        Password: !Ref ProducerStewardUserPassword
        PasswordResetRequired: false
      UserName: ProducerSteward
  ProducerStewardUserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLakeFormationCrossAccountManager'
      Path: /
      Policies:
        - PolicyName: LF-DataLake-Admin-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lakeformation:*'
                  - 'cloudtrail:DescribeTrails'
                  - 'cloudtrail:LookupEvents'
                  - 'glue:GetDatabase'
                  - 'glue:CreateDatabase'
                  - 'glue:UpdateDatabase'
                  - 'glue:DeleteDatabase'
                  - 'glue:SearchTables'
                  - 'glue:CreateTable'
                  - 'glue:UpdateTable'
                  - 'glue:DeleteTable'
                  - 'glue:Get*'
                  - 'glue:List*'
                  - 'glue:BatchGetWorkflows'
                  - 'glue:DeleteWorkflow'
                  - 'glue:GetWorkflowRuns'
                  - 'glue:StartWorkflowRun'
                  - 'glue:GetWorkflow'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                  - 's3:ListAllMyBuckets'
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketPolicy'
                  - 's3:GetBucketPolicyStatus'
                  - 's3:PutBucketPolicy'
                  - 's3:DeleteBucketPolicy'
                  - 'access-analyzer:ValidatePolicy'
                  - 'iam:ListUsers'
                  - 'iam:ListRoles'
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                  - 'iam:PutRolePolicy'
                  - 'iam:CreateServiceLinkedRole'
                  - 'cloudformation:*'
                  - 'elasticmapreduce:*'
                  - 'tag:Get*'
                  - 'glue:BatchGetCrawlers'
                  - 'glue:StartCrawler'
                  - 'glue:UpdateCrawler'
                  - 'iam:Passrole'
                  - 'cloudshell:*'
                Resource: '*'
  AddProducerStewardToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref ProducerStewardUserGroup
      Users:
        - !Ref ProducerStewardUser
    DependsOn:
      - ProducerStewardUserGroup
      - ProducerStewardUser
  LFDataLakeSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: !GetAtt 'ProducerStewardUser.Arn'


Outputs:
  creditBucket:
    Value: !Ref creditBucket
  ProducerStewardUserId:
    Description: User ID for Producer Steward User
    Value: ProducerSteward
  AWSGlueServiceRole:
    Value: !Ref AWSGlueServiceRole
